# Generated by Django 3.1.2 on 2020-10-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0002_auto_20201010_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Telefono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
