# Generated by Django 3.1.2 on 2020-10-24 22:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0003_auto_20201020_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='Apellido',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='FechaN',
            new_name='fechaN',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='Telefono',
            new_name='telefono',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='passwordC',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
