# Generated by Django 3.1.2 on 2020-10-24 23:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_auto_20201024_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('85414d5d-20a1-4205-8d3e-940ff58af098'), primary_key=True, serialize=False),
        ),
    ]
