# Generated by Django 3.1.2 on 2020-10-25 00:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_auto_20201024_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('782b6d03-66a3-400e-9b54-c4a91bd54bfc'), primary_key=True, serialize=False),
        ),
    ]
