# Generated by Django 3.1.2 on 2020-10-25 00:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_auto_20201024_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd61beb6-adf2-444e-a4c7-42c402c2d213'), primary_key=True, serialize=False),
        ),
    ]
